print("\tCadastro de Alunos: ")
print("---------------------------")
print("\tDados pessoas: ")
nome_aluno = str(input("Informe o nome do aluno: "))
idade_aluno = int(input(("Informe idade do aluno: ")))
sexo_aluno = str(input("Informe sexo do aluno(M, F): "))
print("\tDados escola: ")
serie_aluno = str(input("Informe serie do aluno(F, M ou S): "))
turno_aluno = str(input("Informe turno do aluno(M, T): "))
print()
print("\tDados do aluno: ", end='\n')
print(f"Nome: {nome_aluno}, Idade: {idade_aluno}, Sexo: {sexo_aluno}")
print(f"Serie: {serie_aluno}, Turno: {turno_aluno}")
print("---------------------------")
